### ISSUE TITLE
Non-logical function

### ISSUE THREAD

**Issue by dxcore35** [lynchjames/obsidian-day-planner#1]
Tasks in the past will be checked and marked as complete.
What is the purpose of this? The task should be strikeout when I really perform the task, this should be done manually.

**Comment by lynchjames** [comment]
Th plugin provides a day planner (similar to [Focus List](http://focuslist.co) or [Org-Mode Pomodoro](https://www.freelancingdigest.com/articles/pomodoro-emacs-with-orgmode/)) rather than a todo list of items to be checked off manually when completed. 

Checkboxes are used because they are a good markdown native way to present the complete and incomplete state of an item. 

An alternative would be to use 
strikethrough for past items to give this:

- ~15:30 Example Task~

Or even

- 15:30 Example Task||->->->->->->->->->->->->->->->->->->->->||

instead of what is used currently:

- [x] 15:30 Example Task

Which would you prefer?

I will ask for more feedback from others as well and then update based on what most people would prefer as the format for past items.

**Comment by manassadasivuni** [comment]
I think that the first option with the ~~strikeout~~ would be better since it shows that the task is over even with a quick glance

**Comment by dxcore35** [comment]
Maybe if the task time is already over, it should be just grey out.
After this user can check the checklist by them self.

By this solution it can be used as checklist but also as extended live view of current and next tasks...

**Comment by lynchjames** [comment]
Perhaps a couple of config settings may be needed for different use cases. We could have:

**Task Format** (dropdown)
- Bulleted list `- HH:mm Task text`
- Numbered list `1. HH:mm Task text`
- Checkboxes `- [ ] HH:mm Task text`

**Mark Past Items as Complete** (TRUE/FALSE switch)
If set as TRUE, past tasks will be updated to either be checked for checkboxes or have strikethroughs for bulleted and numbered lists.
If set as FALSE, past tasks will not be updated.

**Comment by dxcore35** [comment]
Don't over kill it....
Keep standard markdown [x] and [ ] for manual marking if the task is done.
Make just CSS color change of tasks that are passed based on current time.

Don't screw up the markdown formatting for tasks with some new TRUE/FALSE switch).
