### ISSUE TITLE
Deleting past lines in day planner

### ISSUE THREAD

**Issue by tgrosinger** [lynchjames/obsidian-day-planner#16]
There are two cases I have found where past items in the day planner are being deleted. In both of these cases I am using command mode. I filed #15 about removing the mandatory template insertion that you will see in the demos.

In this first case, I am incorrectly using 12h time instead of 24h. While this is my mistake, it would be nice if there was a warning, rather than just deleting a bunch of lines. Not that the current system time is about 2:35.

![DayPlannerIncorrectTimeFormat](https://user-images.githubusercontent.com/597386/98742363-2d14bb80-2363-11eb-9dc0-fee5eee0602f.gif)

In the second case I am using the right time format, but it still deletes a bunch of lines.

![DayPlannerDeletingItems](https://user-images.githubusercontent.com/597386/98742399-474e9980-2363-11eb-8566-e83fd2e6af08.gif)

**Comment by lynchjames** [comment]
Thanks for raising and providing the steps to reproduce.

The [format currently supported](https://github.com/lynchjames/obsidian-day-planner#day-planner-note) is 24h time with a `HH:mm` format so `09:30` instead of `9:30`. 

I will try and update the regex and parsing to support both `HH:mm` an `H:mm` as I have used this format myself accidentally several times in the early morning and it is reasonable to expect this to work and not remove entered items.

**Comment by tgrosinger** [comment]
Ah great, that does seem to fix it. Thank you 😃

**Comment by lynchjames** [comment]
`H:mm` is now supported although it will be automatically update to `HH:mm` because, among other things, the latter format is required for mermaid.

Also see update in #19 and release [0.3.3](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.3.3) to preserve nested items/sub-tasks.

**Comment by tgrosinger** [comment]
Nice, thank you :-)
