### ISSUE TITLE
Day Planner doesn't find existing "# Day Planner" heading, linking doesn't work

### ISSUE THREAD

**Issue by rklasen** [lynchjames/obsidian-day-planner#26]
Hi, thanks for this fantastic plugin, I've been using it daily since I found it!

I have added the "#Day Planning" heading to my daily note template already, so whenever I create today's note, the planning heading is already there. Unfortunately, the planner plugin doesn't seem to recognize that, I assume it keeps a separate database?

The option "Day Planner: Link today's Day Planner to the current note" from the command palette doesn't seem to have any effect either, but maybe I'm using it wrong.

Best regards!

**Comment by lynchjames** [comment]
Yes, the links between a markdown files and a particular date are stored in plugin data (alongside the plugin settings) so that a day planner can be added to any note. 

Could you post the example of the tasks content you have when trying to link the note? Also, are there any errors in the console when you try to use the link command?

**Comment by rklasen** [comment]
I feel a little silly now. I made a mistake in the heading, it was `#  Day Planner` when it should have been `# Day Planner`. There was an extra white space in between the hash and the word `Day.`

Linking now works just as expected, sorry for the pointless bug report.

Though now while I'm at it, could you add notifications? An error notification like "Required Heading not found" or the like would have been great. And maybe a notification when the day planner was successfully linked.
