### ISSUE TITLE
Note switches between code block and the normal look as I try to change it

### ISSUE THREAD

**Issue by trickstur** [lynchjames/obsidian-day-planner#39]
When I open my day planner note and try to type in it, it changes from the normal appearing text that's like - [ ] Text to a giant code block and is not able to be typed in. Additionally, I'm getting (and I feel like this is the culprit) conflicted copies in my folder anytime I do make a change. I entered in a template earlier and since then it's gone crazy. I'm positive I only inserted the template once, and I've checked the template out, everything should be fine. But the note doesn't look ok. 

The version installed is 0.5.3 and I have version 0.9.19 of Obsidian. I use dropbox to sync my notes, however my other notes I've created today are not having syncing issues. I had to zip the file because .md isn't supported. I should add at one point I did have mermaid gantt chart on, but I turned it off. 

[Day Planner-20201201.md.zip](https://github.com/lynchjames/obsidian-day-planner/files/5625739/Day.Planner-20201201.md.zip)

**Comment by trickstur** [comment]
![6b0e30391339d1dfb4d109f41667b43d](https://user-images.githubusercontent.com/10410256/100803397-19f08b00-33f9-11eb-98c8-e79948934d69.gif)

**Comment by trickstur** [comment]
What it should look like: 
![image](https://user-images.githubusercontent.com/10410256/100803608-73f15080-33f9-11eb-8c91-2b5b00594b2b.png)

**Comment by lynchjames** [comment]
Thanks for this info and the example file. 

I think I see what is happening. The generated mermaid block has been corrupted some how so that it is including task `- [ ]` items. This is causing the code block to be parsed which then generated duplicate content added to the note.

I'll look at preventing task items in a mermaid code block from causing duplicate content being generated in the note. 

In the mean time, if you remove the mermaid code block you should avoid having issues with duplicate content in the note and knock on issues with file syncing etc. You may have to unlink the note from the day planner to remove the code block or change it in a different note and copy the content into your day planner note.

Remove this..
```
    ```mermaid
    - [ ] 09:30 Wake Up
    ...
    ```
```

**Comment by lynchjames** [comment]
Some recent changes to the way the note content is parsed should have resolved this issue so I will close. Please reopen if you are still seeing the issue arise in the latest version of the plugin.
